{% set version = "4.0.0" %}

package:
  name: jupyterlab-github
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-github/jupyterlab_github-{{ version }}.tar.gz
  sha256: fab84e981684753f35bc5b55f8e84a30ffbe5b642d7b2d2721e4a048896afa54
 
build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.5.0
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - jupyterlab >=4.0.0,<5
    - pip
    - python >=3.8
  run:
    - jupyterlab >=4.0.0,<5
    - python >=3.8

test:
  imports:
    - jupyterlab_github
  requires:
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyterlab/github.*OK.*jupyterlab_github" labextensions
    # tests jupyter_server machinery
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - grep -iE "jupyterlab_github.*OK" server_extensions

about:
  home: https://github.com/jupyterlab/jupyterlab-github
  summary: JupyterLab viewer for GitHub repositories
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
